### ISSUE TITLE
[QUESTION/DISCUSSION] readme for assignment/

### ISSUE THREAD

**Issue by tanner-g** [VulnerabilityHistoryProject/httpd-vulnerabilities#14]
# Questions about assignment/README
- [x] do the links to the CVEs need to be updated to something you have elsewhere or just removed from instructions?
- [x] does the consent form for chromium apply to this repo too?
- [x] can I add in git commands to the readme (i.e. git clone ....) or is the goal for that to be learned. 
     I ask because in some parts of the directions there are links to guides, but in other places it is provided.
- [x] what is the recommended place to look at httpd souce code?
    https://httpd.apache.org/ ?

**Comment by andymeneely** [comment]
git://git.apache.org/httpd.git

**Comment by andymeneely** [comment]
Consent form is the same

**Comment by andymeneely** [comment]
Yes, go ahead and add in commands to the README. Make it make sense for this project
