### ISSUE TITLE
does published date = announced date?

### ISSUE THREAD

**Issue by tanner-g** [VulnerabilityHistoryProject/httpd-vulnerabilities#4]
got all the dates for our current CVEs. after looking at the skeleton yml files, i wonder if we should make a new field?

**Comment by andymeneely** [comment]
Yes, we can count them as the same. Technically they can be different, but they'll generally be the same.

**Comment by tanner-g** [comment]
ok cool! Then I'm going to a script to put these dates into the final yml files.

**Comment by tanner-g** [comment]
decided to have two tags. published date and date security team reports maybe different. moving to two other issues for tracking this.
